# -*- coding: utf-8 -*-
"""品質管製圖.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBl_8mzjCptIVJcWGr-q0FTr2nEXllIQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. 建立/讀取數據 (假設有 15 個子組，每個子組抽樣 10 個數據，即 C16:L16 共 10 個欄位)
df = pd.read_excel('data.xlsx')
#np.random.seed(42)
# 模擬 15 組、每組 10 個測量值的矩陣
data = np.random.normal(loc=10.0, scale=0.5, size=(15, 10))

# 2. 統計量計算 (對每個子組 row 進行計算)
x_bar = np.mean(data, axis=1)          # 各子組平均值 (X-bar)
sample_std = np.std(data, axis=1, ddof=1) # 各子組標準差 (對應 VBA 的 StDev_S)
sample_range = np.ptp(data, axis=1)    # 各子組全距 (Max - Min)

# 3. 計算中心線 (CL) 與參數 
grand_mean = np.mean(x_bar)            # X-bar 的中心線 CL
p5_std = np.mean(sample_std)           # 平均標準差 (即圖片 VBA 中的 P5 變數)
cl_r = np.mean(sample_range)           # R chart 的中心線 CL

# --- X-bar Chart 控制界限  ---
ucl_x = grand_mean + 1.023 * p5_std
lcl_x = grand_mean - 1.023 * p5_std

# --- R Chart 控制界限  ---
ucl_r = 2.574 * p5_std
lcl_r = 0.0 * p5_std

# 4. 畫圖：繪製 X-bar Chart 與 R Chart
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
subgroups = np.arange(1, len(x_bar) + 1)

# ----- X-bar Chart -----
ax1.plot(subgroups, x_bar, marker='o', color='b', linestyle='-', linewidth=1.5, label='X-bar (Subgroup Mean)')
ax1.axhline(grand_mean, color='green', linestyle='--', label=f'CL = {grand_mean:.3f}')
ax1.axhline(ucl_x, color='red', linestyle=':', linewidth=1.5, label=f'UCL = {ucl_x:.3f}')
ax1.axhline(lcl_x, color='red', linestyle=':', linewidth=1.5, label=f'LCL = {lcl_x:.3f}')
ax1.set_title("X-bar Chart", fontsize=14, fontweight='bold')
ax1.set_ylabel("Sample Mean")
ax1.legend(loc='upper right')
ax1.grid(True, linestyle='--', alpha=0.5)

# ----- R Chart -----
ax2.plot(subgroups, sample_range, marker='s', color='orange', linestyle='-', linewidth=1.5, label='Range (R)')
ax2.axhline(cl_r, color='green', linestyle='--', label=f'CL = {cl_r:.3f}')
ax2.axhline(ucl_r, color='red', linestyle=':', linewidth=1.5, label=f'UCL = {ucl_r:.3f}')
ax2.axhline(lcl_r, color='red', linestyle=':', linewidth=1.5, label=f'LCL = {lcl_r:.3f}')
ax2.set_title("R Chart", fontsize=14, fontweight='bold')
ax2.set_xlabel("Subgroup Number")
ax2.set_ylabel("Sample Range")
ax2.legend(loc='upper right')
ax2.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

# 1. 建立計數型數據（假設 20 批次，每批抽樣 n=100，紀錄不良個數 d）
n = 100
subgroups_attr = 20
d_counts = np.random.binomial(n=n, p=0.04, size=subgroups_attr)
d_counts[8] = 12  # 人為注入異常點

# 2. 計算 p (不良率) 與統計量
p_array = d_counts / n
p_bar = np.mean(p_array)             # 平均不良率 p-bar
d_bar = n * p_bar                    # 平均不良數 d-bar (np-bar)

# p-chart 管制界限
std_p = np.sqrt(p_bar * (1 - p_bar) / n)
UCL_p = p_bar + 3 * std_p
LCL_p = max(0, p_bar - 3 * std_p)

# d-chart (np-chart) 管制界限
std_d = np.sqrt(n * p_bar * (1 - p_bar))
UCL_d = d_bar + 3 * std_d
LCL_d = max(0, d_bar - 3 * std_d)

# 3. 繪製 p-chart & d-chart
fig2, (ax3, ax4) = plt.subplots(2, 1, figsize=(10, 7), sharex=True)
x_attr = np.arange(1, subgroups_attr + 1)

# p-Chart
ax3.plot(x_attr, p_array, marker='o', color='purple', linestyle='-')
ax3.axhline(p_bar, color='g', linestyle='--', label=f'CL = {p_bar:.3f}')
ax3.axhline(UCL_p, color='r', linestyle=':', label=f'UCL = {UCL_p:.3f}')
ax3.axhline(LCL_p, color='r', linestyle=':', label=f'LCL = {LCL_p:.3f}')
# 標註超出 UCL 的異常點
out_p = (p_array > UCL_p) | (p_array < LCL_p)
ax3.plot(x_attr[out_p], p_array[out_p], 'ro', markersize=10, fillstyle='none', markeredgewidth=2, label='Out of Control')
ax3.set_title("p-Chart (Proportion Defective)")
ax3.set_ylabel("Defective Rate (p)")
ax3.legend(loc='upper right')
ax3.grid(True, linestyle='--', alpha=0.5)

# d-Chart (np-Chart)
ax4.plot(x_attr, d_counts, marker='s', color='brown', linestyle='-')
ax4.axhline(d_bar, color='g', linestyle='--', label=f'CL = {d_bar:.2f}')
ax4.axhline(UCL_d, color='r', linestyle=':', label=f'UCL = {UCL_d:.2f}')
ax4.axhline(LCL_d, color='r', linestyle=':', label=f'LCL = {LCL_d:.2f}')
# 標註超出 UCL 的異常點
out_d = (d_counts > UCL_d) | (d_counts < LCL_d)
ax4.plot(x_attr[out_d], d_counts[out_d], 'ro', markersize=10, fillstyle='none', markeredgewidth=2, label='Out of Control')
ax4.set_title("d-Chart / np-Chart (Number of Defectives)")
ax4.set_xlabel("Subgroup Number")
ax4.set_ylabel("Defective Count (d)")
ax4.legend(loc='upper right')
ax4.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()
